# Librería Numpy

La librería numpy ofrece funciones eficientes para la manipulación y el procesamiento numérico en arrays.

Este tipo de estructuras de almacenamiento númerico no son exactamente listas aunque puedan aparentar ese comportamiento (*duck-style*). Sus elementos son homogéneos e incluyen operaciones básicas y operaciones más complejas como álgebra lineal.

Numpy forma parte del *core* de otras librerías como Pandas.


https://numpy.org/doc/stable/index.html


mediante el siguiente magicomand veremos si tenemos la librería numpy instalada (SO requerido: Mac o Linux, o en Google Colab)

In [ ]:
!pip freeze | grep numpy


In [ ]:
import numpy as np

data = np.array([1,0]) 
print(data[0])
print(type(data[0]))

data = np.array([[1,0],[2,0],[3,0]])
print(data[0][:0])


In [ ]:
print(data.shape)
print(data.size)
print(data.ndim)
print(data.dtype)

Tipos de datos soportados:

- int: int8, int16, int32, int64
- uint: uint8, uint16, uint32, uint64
- bool: Bool
- float: float16, float32, float64, float128
- complex: complex64, complex128, complex256 

In [ ]:
data = np.array([[1,0],[2,0]],dtype=np.int32)
data = np.array([[1,0],[2,0]],dtype=np.complex64)
data = np.array([[1,0],[2,0]],dtype=np.float16)
# Conversión
data = np.array(data,dtype=np.uint)
data = data.astype(np.bool_)
print(data)

## Generación 

No todo es cargar valores. A veces es necesario generar una muestra de puntos aleartoria, un vector neutro, o escala de valores.

In [ ]:
data = np.array(range(10))
print(data)

data = np.arange(10)
print(data)

data = np.zeros((10,5))
# https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
print(data)

data = np.ones(10)
print(data)

In [ ]:
shape = (10,80) # 10 rows x 80 cols
data = np.zeros(shape)
print(data)

In [ ]:
data = np.linspace(0,1,10)
print(data)

In [ ]:
data = np.logspace(0,2,10) # 10puntos entre 2**0 y 2**2
print(data)

In [ ]:
data = np.identity(3)
print(data)
print("-"*10)

data = np.eye(3,k=1) # https://numpy.org/doc/stable/reference/generated/numpy.eye.html
print(data)
print("-"*10)

data = np.diag(range(1,4))
print(data)


### Generación o sampling aleatorio

In [ ]:
data = np.random.rand(3,3)
print(data)
print("-"*20)

data = np.random.randint(1,10,size=(2,2))
print(data)
print("-"*20)

data = np.random.randint(1,10,20).reshape(10,2)
print(data)
print("-"*20)

data = np.array(np.random.rand(20)*10,dtype=int).reshape(10,2)
print(data)

## Actividades

### Actividad 1
Imaginad la siguiente actividad donde tenemos que realizar la siguiente matriz:

```
array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
```

tip: https://numpy.org/doc/stable/reference/generated/numpy.repeat.html

In [ ]:
# TODO ACTIVITY

### Actividad 2

Generar la siguiente estructura a partir del array([1, 2, 3])

```
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

tip: https://numpy.org/doc/stable/reference/generated/numpy.tile.html


In [ ]:
# TODO Activity

## Carga y volcado de datos

Entrada y salida

¿Cómo cargar datos de un fichero y cómo salvar resultados?

Siempre hay  que considerar el tipo de formato con el que se han guardado los datos. El formato influye en el rendimiento de las operaciones (R/W) y la capacidad de almacenamiento utilizada.
- CSV suele contener texto, no es eficiente, pero fácil de ingerir en otras herramientas. ¿Tiene sentido un fichero csv para matrices númericas? https://datos.gob.es/es/catalogo
  
- Formatos binarios:
  - npy, npz propios de numpy
  - pickle - https://docs.python.org/3/library/pickle.html

## Carga de datos con Pandas a Numpy (solución no-ideal)

Vamos a utilizar cualquier fichero csv (i.e. altura de gabilos) para tener en una estructura de numpy dichos valores de altura.

In [ ]:
!cat data/"GALIBOS TUNELES MADRID".csv

**Recomendaciones** No pongais nombres de ficheros con espacios ni con acentos! 

In [ ]:
import pandas as pd
df = pd.read_csv("data/GALIBOS TUNELES MADRID.csv",sep=";")
df.columns
height = df[df.columns[1]]
print(height)
## ACTIVIDAD: Como solucionaomos este error!!!!!!!!

data = np.array(height,np.float32)
print(data)

#### Usando métodos de numpy



In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html
data = np.loadtxt("data/GALIBOS TUNELES MADRID.csv", delimiter=";", usecols = (1), skiprows=1, converters={1: lambda s:float(str(s.decode()).replace(",","."))})
print(data)
print(data.shape)

### Volviendo a trabajar con datos numéricos

In [ ]:
data = np.random.uniform(0.01,20.0,size=100000)
print(data[:5])

In [ ]:
f = open("data/tmp.npy","wb") # Writing file, in Binary mode
np.save(f,data)
f.close()

with open("data/tmp2.csv","w") as f2: # Writing but in txt
    for n in data:
        f2.write(str(n)+",")


In [ ]:
!ls -lih data/tmp*

In [ ]:
data = np.random.uniform(0.01,20.0,size=100000)
data2 = np.random.normal(0.3,10,100000)
print(data[:5])
print(data2[:5])

f = open("data/tmp.npy","wb") # Writing file, in Binary mode
np.save(f,data)
np.save(f,data2)
f.close()

print("saved")


with open('data/tmp.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)

print(a[:5])
print(b[:5])


In [ ]:
import pickle

with open("data/tmp3.npy",'wb') as f:
    pickle.dump(a, f)
    pickle.dump(b, f)
    

In [ ]:
!ls -lih data/tmp*

In [ ]:
f = "data/tmp3.npy"
ca = pickle.load(open(f,"rb"))
print(ca)
cb = pickle.load(open(f,"rb"))
print(cb)

# Qué paso en este punto?
# ¿Cómo podriamos haber guardado ambas variables dentro del mismo fichero?

## Operaciones con series numpy

In [ ]:
import numpy as np
a = np.array([.0,0.1])
b = np.array([1,1])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(2**a)

In [ ]:
c = np.array([1,1,1])
print(a+c) #Alerta

In [ ]:
c = np.array([1,1,1,1]).reshape(2,2)
print(a*c)
print("-"*10)
print(a.dot(c)) #https://numpy.org/doc/stable/reference/generated/numpy.dot.html


In [ ]:
# Tensor dot 
#https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html#numpy.tensordot
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print(c)
print(c.shape)

In [ ]:
# Einseum 
# https://numpy.org/doc/stable/reference/generated/numpy.einsum.html

a = np.arange(25).reshape(5,5)
np.einsum("ii",a)

#### Kron product
https://en.wikipedia.org/wiki/Kronecker_product

$$a \otimes b$$

In [ ]:
a = np.arange(1,5).reshape(2,2)
print(a)
b = np.array([0,5,6,7]).reshape(2,2)
print(b)
print("-"*10)
k = np.kron(a,b)
print(k)


### Actividad
Implementa con operaciones básicas de numpy la multiplicación de Kron.<br/>
Compara tiempos de ejecución entre tú versión y la ya implementada.

In [ ]:
#TODO Activity

## Funciones sobre series

In [ ]:
a = np.array(range(10))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))

In [ ]:
print(np.sum(a))
print(np.cumsum(a))
print(np.mean(a))

print("\n",np.cumprod(a))
print(np.min(a))
print(np.argmax(a))


In [ ]:
print(a.mean())
print(a.min())
print(a.argmax())

In [ ]:
a = a.reshape(2,5)
print(a)
print("-"*10)
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))

## Actividades

### Actividad. 1

¿Cómo calcular la distancia euclidea entre dos vectores?
$$ d{v_1,v_2}=\sqrt{\sum_{k=1}^n(x_{1,k}-x_{2,k})^2} $$

In [ ]:
v1 = np.arange(1,4)
v2 = np.arange(4,7)
#TODO Activity
# Solucion == 5.196152422706632

### Actividad. 2

¿Y calcular la distancia de Manhattan?

$$ d{v_1,v_2}= \sum_{k=1}^n \mid x_{1,k} - x_{2,k} \mid $$

In [ ]:
v1 = np.arange(1,4)
v2 = np.arange(4,7)
#TODO Activity
# Solucion == 9

## Restructurando la dimensión de una serie

In [ ]:
a = np.arange(10)
print(a.shape)
print(a.reshape(2,5))
print(a)


In [ ]:
a = a.reshape(2,5)
print(a.T)
print("-"*10)
print(np.hstack(a))  # https://numpy.org/doc/stable/reference/generated/numpy.hstack.html


In [ ]:
b = np.arange(10,20).reshape(2,5)
print(b)
print("-"*10)
print(np.hstack((a,b))) # axis-1
print(np.vstack((a,b))) # axis-0


In [ ]:
c = np.dstack((a,b)) # axis-2  https://numpy.org/doc/stable/reference/generated/numpy.dstack.html
print(c)
print(c.shape)

In [ ]:
print(a)
print(np.ravel(a)) # https://numpy.org/doc/stable/reference/generated/numpy.ravel.html

print(np.ravel(a,order="F")) # ‘F’ means to index the elements in column-major,

In [ ]:
print(a)
print(np.split(a,2))
c1,c2 = np.split(a,2)

print("-"*10)

print(c1)
print(c1.shape)
print(np.ravel(c1))
print(c2)

In [ ]:
print(np.concatenate((a,b)))
print("-"*10)
print(np.concatenate((a,b),axis=1))

In [ ]:
# https://pillow.readthedocs.io/en/stable/

In [ ]:
%pip install pillow

In [ ]:
from PIL import Image

image = Image.open('images/gatito.jpeg')
# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)

display(image)


In [ ]:
data = np.asarray(image)
print(len(data[0]))
print(data.size)
print(data.shape)
w,h,_ = data.shape

In [ ]:
print(data[w//2,h//2])
data2 = data.copy()
data2[w//2,h//2] = np.array([255,0,0]) # a red point

img = Image.fromarray(data2, 'RGB')

display(img)


In [ ]:
center_mask = w//2,h//2
rectangle_size = int(w*0.1)
mask = np.ones(rectangle_size*rectangle_size).reshape(rectangle_size,rectangle_size)
print(mask.shape)

for x in range(w//2,w//2+rectangle_size):
    for y in range(h//2,h//2+rectangle_size):
        data2[x,y] =  np.array([255,0,0])


img = Image.fromarray(data2, 'RGB')
display(img)

# REALMENTE, el cuadrado está en el centro?


## Actividad

Transforma la imagen en tonos grises. Solo con numpy!!!

In [ ]:
#WAY 1:
# 
data = np.asarray(image)
data2 = data.copy()
for x in range(data2.shape[0]): #no eficiente
     for y in range(data2.shape[1]):
         data2[x,y] = np.repeat(data[x,y].mean(),3)

img = Image.fromarray(data2, 'RGB')
display(img)

## Operaciones de Slicing

In [ ]:
a = np.arange(300).reshape(10,10,3)
print(a[:1])
print("-"*10)

print(a[0][0])
print("-"*10)

print(a[:,0])
print("-"*10)

print(a[:,2:4])
print("-"*10)

In [ ]:
a = np.arange(300).reshape(10,10,3)
print(a[:1])
print("-"*10)

print(a[:,:,0])

print("-"*10)

r = 0.2126
print(a[:,:,0]*r)


In [ ]:
# WAY2
# https://e2eml.school/convert_rgb_to_grayscale.html


# TODO

print(data.shape)
img = Image.fromarray(np.uint8(data))
display(img)



In [ ]:
# Way 3

rgbcorrection = np.array([0.2989, 0.5870, 0.1140])

data = np.asarray(image)
print(data.shape)
data2 = np.dot(data,rgbcorrection)

print(data2.shape)
img = Image.fromarray(np.uint8(data2))
display(img)


# as a plot
import matplotlib.pyplot as plt
plt.imshow(data2, cmap = plt.get_cmap(name = 'gray'))
plt.show()

## Funciones propias vectorizadas


In [ ]:
temperatura = np.random.randint(-10,43,1000)

In [ ]:
temperatura[temperatura>33]

In [ ]:
def isHot(grados):
    if grados>33 and grados<=40:
        return True

def isHot(grados):
    return grados>33 and grados<=40
        
fHot = np.vectorize(isHot)
print(fHot(temperatura))

In [ ]:
temperatura[fHot(temperatura)]

In [ ]:
#Alternativa
# https://numpy.org/doc/stable/reference/routines.logic.html
np.logical_and(temperatura>30,temperatura<=40)

In [ ]:
isHot = lambda x: (x>30 and x<=40)
index = list(map(isHot,temperatura))
temperatura[index]

### Más funciones lógicas

In [ ]:
np.random.seed(2022)
a = np.random.randint(-90,0,100)

index = np.where(a<-80) # Alerta: Son índices
print(index)
print(a[index])

In [ ]:
print(np.logical_or(a<-80,a<-90))


In [ ]:
print(np.logical_not(np.logical_or(a<-40,a<-90)))

### Actividades

¿Cómo podemos conseguir esta transformación?

De
```
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
a
```
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

## Operaciones con Grupos

In [ ]:
np.random.seed(2022)
a = np.random.randint(-30,45,100)
print(a)

In [ ]:
9 in a

In [ ]:
if -14 in a and not -6 in a:
    print("Something strange")
elif 45 in a:
    print("No 11")
else:
    print("Pues está el -14 y el -6, y no el 45")

In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.unique.html?highlight=unique#numpy.unique

unique_a = np.unique(a)  # sort but
print(unique_a)

In [ ]:
unique_a, freq_a = np.unique(a,return_counts=True) 
print(a)
print(len(a))
print("-"*10)
print(freq_a)
print(len(freq_a))
print("-"*10)
print(unique_a)
print(len(unique_a))

# ¿Cuántos elementos repetidos hay?

In [ ]:
unique_a,index_a,freq_a = np.unique(a,return_counts=True,return_index=True) 
print(freq_a)
print(index_a)
print("-"*10)
print(np.where(freq_a==4))
print(unique_a[17]) # se repite cuatro veces
print(unique_a[33]) # se repite cuatro veces
print(unique_a[50]) # se repite cuatro veces

print(a[np.where(a==-7)])

In [ ]:
np.sort(freq_a)

In [ ]:

print(np.array([0,4,1,2,5,7,9])[::-1])
print(np.argsort(np.array([0,4,1,2,5,7,9])))
print(np.argsort(np.array([0,4,1,2,5,7,9]))[::-1])

print("-"*10)

index_sorted = np.argsort(freq_a)[::-1] #https://numpy.org/doc/stable/reference/generated/numpy.argsort.html
print(index_sorted)



In [ ]:
unique_a[index_sorted]

### Actividades

#### Actividad 1

- ¿Cuál es el color más frecuente en la imagen del gatito?
- Sustituye esos pixeles por un color azul: rgb=(0,0,255)

In [ ]:
from PIL import Image

image = Image.open('images/gatito.jpeg')
#TODO


In [ ]:
a = np.arange(10)
b = np.arange(5,15)
print(a)
print(b)
print("-"*10)
print(np.in1d(a,b))
print(np.intersect1d(a,b))
print("-"*10)
print(np.setdiff1d(a,b))
print(np.setdiff1d(b,a))
print("-"*10)
print(np.union1d(a,b))

#### Actividad 2

¿Cómo podemos conseguir encontrar valores pico, valores mayores sobre sus vecinos?

```
array([0, 1, 2, 3, 4, 54, 6, 7, 80, 9])
array([5, 8])
```

Un par de pistas: 
- np.diff https://numpy.org/doc/stable/reference/generated/numpy.diff.html?highlight=diff#numpy.diff
- np.sign https://numpy.org/doc/stable/reference/generated/numpy.sign.html?highlight=sign#numpy.sign
- 
  

In [ ]:
a = np.array([0, 1, 2, 3, 4, 54, 6, 7, 80, 9])
# TODO

#### Actividad 3

Existe alguna columna o fila que sólo tenga una única incógnita?
```
sudoku = np.array([[5,3,0,0,7,0,0,0,0],
                 [6,0,0,1,9,5,0,0,0],
                 [1,9,8,0,0,0,0,6,0],
                 [8,0,0,0,6,0,0,0,3],
                 [4,0,0,8,0,3,0,0,1],
                 [7,0,0,0,2,0,0,0,6],
                 [0,6,0,0,0,0,2,8,0],
                 [3,8,0,4,1,9,7,2,5],
                 [4,0,0,0,8,0,0,7,9]])

```

## Funciones de estadística

In [ ]:
np.random.seed(2022)
temperatures= np.random.normal(loc=17,scale=20,size=1000000)


# https://numpy.org/doc/stable/reference/routines.statistics.html

print(temperatures.mean())


In [ ]:
import matplotlib.pyplot as plot

fig, ax = plot.subplots()
ax.plot(np.sort(temperatures))

In [ ]:
np.quantile(temperatures,0.5)

In [ ]:
np.percentile(a,90) #https://numpy.org/doc/stable/reference/generated/numpy.percentile.html#numpy.percentile

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.histogram.html#numpy.histogram
hist, bin_edges = np.histogram(temperatures)
print(hist)
print(bin_edges)

print(np.sum(hist))


In [ ]:
import matplotlib.pyplot as plt
_ = plt.hist(temperatures, bins='auto')  # arguments are passed to np.histogram
plt.title("Histogram with 'auto' bins")
plt.show()

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

space = np.linspace(0,1,len(temperatures))
print(space[:10])

In [ ]:
import matplotlib.pylab as plt

temperatures_sorted = np.sort(temperatures)
fig, ax = plt.subplots()
ax.plot(temperatures_sorted,space)
#CDF?

# Gestión de alertas y errores 

In [ ]:
a , b = 0, 3
c = b/a

In [ ]:
a , b = 0, 3
try:
    c = b/a
except:
    print("error")
finally:
    print("Intento realizar una linea alternativa de ejecucion")

print("ESto siguye")

In [ ]:
a , b = 0, 3
try:
    c = b/a
except ZeroDivisionError:
    print("error")
finally:
    print("Intento realizar una linea alternativa de ejecucion")

In [ ]:
a , b = 0, 3
d={"a":0,"b":-1}
try:
    print(d["c"])
except ZeroDivisionError:
    print("error")
finally:
    print("Intento realizar una linea alternativa de ejecucion")

In [ ]:
a , b = 0, 3
d={"a":0,"b":-1}
try:
    print(d["c"])
except ZeroDivisionError:
    print("hay un cero")
except KeyError:
    print("Key no existente")
finally:
    print("Intento realizar una linea alternativa de ejecucion")

Docs : https://docs.python.org/3/tutorial/errors.html

In [ ]:
a , b = np.arange(10), np.arange(10,20)

c = b/a
print(c)

In [ ]:
import math
print(math.inf in c)
print(c * np.random.rand(10))

In [ ]:
try:
    c = b/a
except RuntimeWarning:
    print("Capturo warning ? ") # No

In [ ]:
# Puedo ignorarlos
import warnings
warnings.filterwarnings("ignore")
c = b/a
print(c)

In [ ]:
# Puedo gestionarlos como una excepción
np.seterr(all='raise')
c = b/a
print(c)

In [ ]:
try:
    c = b/a
except FloatingPointError:
    print("Capturo warning ? ") # Yes

## Reflexiones sobre el rendimiento computacional y algorítmico

Principales métricas percibidas por el usuario:
- *tiempo de respuesta*, tiempo de servicio y tiempo de espera

Principales métricas para el sistema:
- Productividad (trabajos/tiempo)

Las métricas están influidas porque hay una *demanda* sobre el servicio. Mayor demanda ->  ???

El rendimiento está influido por:
- Hardware: tecnología, arquitectura, 
- Software: sistemas operativos, lenguaje de programación, aplicaciones 
- *Vuestra manera de programar!*

In [ ]:
import time

start = time.time()
# do something
print("Response time: %s seconds"%(time.time()-start))

In [ ]:
import numpy as np
import time
serie = np.random.random(10000000)

start = time.time()
b = []
for value in serie:
    try:
        b.append(math.sqrt(value))
    except:
        b.append(0)
end1 = time.time()-start
print("Response time: %s seconds"%(end1))

In [ ]:
start = time.time()
b = np.sqrt(serie)
end2 = time.time()-start
print("Response time: %s seconds"%(end2))

In [ ]:
speedup = end1/end2
print(speedup)
print("El programa 2 es %0.2f veces más rápido que el programa 1"%speedup)

Si necesitáis 1 hora de ejecución del programa 1, con el segundo solo,  3.8199 minutos. <br/>
Si necesitáis 24 horas de ejecución del programa 1, con el segundo solo, 1.527 horas.

<b>Atención</b> las métricas de rendimiento suelen seguir una distribución exponencial. NO SON LINEALES!!!!

In [ ]:
times1 = []
for size in range(10,1000000,1000):
    serie = np.random.random(size)
    start = time.time()
    b = []
    for value in serie:
        try:
            b.append(math.sqrt(value))
        except:
            b.append(0)
    end1 = time.time()-start
    times1.append(end1)

print(".")
times2 = []
for size in range(10,1000000,1000):
    serie = np.random.random(size)
    start = time.time()
    b = np.sqrt(serie)
    end2 = time.time()-start
    times2.append(end2)


In [ ]:
import matplotlib.pyplot as plt
x = list(range(len(times1)))
fig, ax = plt.subplots()
ax.plot(x, times1, label = "programa 1")
ax.plot(x, times2, label = "programa 2")
ax.legend()
plt.show()

# No es suficientemente complejo (o sí -depende de arquitectura) para crear la curva 

### Librería Numba 

https://numba.pydata.org/

In [ ]:
!pip install numba

In [ ]:
import multiprocessing

multiprocessing.cpu_count()

In [ ]:
from numba import njit
import random


def monte_carlo_pi_sinParalelizar(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return 4.0 * acc / nsamples

@njit
def monte_carlo_pi(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return 4.0 * acc / nsamples

In [ ]:
%timeit monte_carlo_pi_sinParalelizar(100)

In [ ]:
%timeit monte_carlo_pi(100)

### Escenario de mal rendimiento ...

Como traer "mal" datos de una BBDD <br/>
<img src="images/consultaSQL.png" width="80%" />



## Actividad Final

Con estos tres catálogos de datos:
- A) https://datos.gob.es/es/catalogo/ea0010587-balears-illes-por-municipios-y-fenomeno-demografico-mnpd-identificador-api-t20-e301-fenom-a2020-l0-23007-px
- B) https://data.cityofnewyork.us/Housing-Development/Speculation-Watch-List/adax-9mit
- C) https://ec.europa.eu/eurostat/databrowser/view/gov_10a_exp/default/table?lang=en

Debéis analizar o aplicar 4 indicadores mínimos de libre elección. Es decir, según la naturaleza de los datos elegid indicadores estadísticos u otros. Como ejemplo, os proporciono el primero:
- Con A) Series por *nacidos vivos por residencia materna*, Serie ordenada por *fallecidos por el luegar de residencia*, medía y desviación de los cinco indicadores disponibles por municipio
- Con B) ?
- Con C) ?


**REQUISITOS**
- Tenéis que analizar los datos EXCLUSIVAMENTE con la librería de NUMPY
- Se valorará la no inclusión de valores manuales, es decir, que el código sea robusto y lo más genérico posible.
- Se valorará la inclusión de gráficas (plots).

Entrega de la práctica: 
- Se subirá el enlace de vuestro github personal a la *Tarea* específica de Auladigital.
- Se ha de realizar un notebook por cada catálogo de datos.
- Hay que incluir un fichero README.md que contenga el informe de la práctica (indicadores utilizados, y aspectos y conclusiones extraidas de cada uno de ellos)
- Se recomienda la siguiente estructura por directorios: /part2/numpy_activity/notebookA....